version: "3.8"
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - app-network
    restart: unless-stopped

  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
